## Solution 1: Using numpy (However, this solution violated the rules.)

In [13]:
import numpy as np

class Solution(object):
    def rotate(self, matrix):
        length = len(matrix)
        arr = np.array(matrix).T
        arr2 = np.identity(n=length)[::-1]
        return np.dot(arr, arr2)

    
solution = Solution()

matrix = [[1,2,3],[4,5,6],[7,8,9]]
result = solution.rotate(matrix)
print(result)

[[7. 4. 1.]
 [8. 5. 2.]
 [9. 6. 3.]]


Time Complexity: $O(n^3)$

## Solution 2: transpose and row exchange

In [45]:
class Solution(object):
    def rotate(self, matrix):
        length = len(matrix)

        # Transpose
        for i in range(length):
            for j in range(length):
                if i < j:
                    cp = matrix[j][i]
                    matrix[j][i] = matrix[i][j]
                    matrix[i][j] = cp

        # Row exchange
        for i in range(length):
            matrix[i] = matrix[i][::-1]
        return matrix
    
solution = Solution()

matrix = [[1,2,3],[4,5,6],[7,8,9]]
result = solution.rotate(matrix)
print(result)

[[7, 4, 1], [8, 5, 2], [9, 6, 3]]


Time Complexity: $O(n^2)$